apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: anjwz32ub-python 
  janus-idp.io/tekton: anjwz32ub-python
  backstage.io/kubernetes-id: anjwz32ub-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: anjwz32ub-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml